#!/bin/bash

file=keyboard

export PICO_PLATFORM=rp2040
export PICO_BOARD=pico

mkdir -p build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target ${file}

if [[ "$OSTYPE" == "darwin"* ]]; then
	cp src/${file}.uf2 /Volumes/RPI-RP2
else
	cp src/${file}.uf2 /media/$USER/RPI-RP2
fi

cd ..
