#!/bin/bash

file=keyboard

mkdir -p build
cd build
cmake ..
make ${file}

if [[ "$OSTYPE" == "darwin"* ]]; then
	cp src/${file}.uf2 /Volumes/RPI-RP2
else
	cp src/${file}.uf2 /media/$USER/RPI-RP2
fi

cd ..
